# Common properties shared by all profiles
spring:
  profiles:
    active: dev
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  cache:
    type: redis
    redis:
      time-to-live: 1m
      key-prefix: "journal-app-cache::" # Use a specific prefix for all cache keys
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6739
      password: ${REDIS_PASSWORD}
    ssl:
      enabled: false

weather:
  api:
    url: "http://api.weatherstack.com/current"
app:
  jobs:
    quota-report-cron: ${QUOTA_REPORT_CRON}
    quota-reset-cron: ${QUOTA_RESET_CRON}
  quota:
    max: ${QUOTA_MAX}

---
# --- Development Profile ---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      uri: ${MONGO_DB_URI_DEV}
      database: journaldb
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8080
logging:
  level:
    com.myjournal.journalApp: DEBUG
weather:
  api:
    key: ${WEATHER_API_KEY_DEV}

---
# --- Production Profile ---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      uri: ${MONGO_DB_URI_PROD}
      database: journaldb_prod
      auto-index-creation: false # Disable in production
server:
  port: 9090
logging:
  level:
    com.myjournal.journalApp: INFO # Use INFO level in production
weather:
  api:
    key: ${WEATHER_API_KEY_PROD}